Making the portfolio project responsive
cindykandie/microverse-portfolo pull request #6
Opened 2022-12-08 17:43 UTC by cindykandie

## Responsive Web design
- Completed/ made final touches on the mobile design
- Styled my Website to be responsive on both tablet screens by making the most suitable adjustments in the media queries
- Used Chrome dev tools to vie the sit on different size screens
- Used both CSS Grid and Flexbox to layout my sections
- Added various transitions and animations to improve UX(User Experience)

2022-12-08 21:10 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @cindykandie , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media3.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/> |

## Highlights

- [ ]..✅ Descriptive pull request
- [ ]..✅ Good commit messages
- [ ]..✅ Green linters
- [ ]..✅ Good design the way, your app is responsive

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 21:10 UTC, joskalenda commented on css/mediascreen.css
> +  header {
- [x] Your website is responsive, and I appreciate it, however, there are a few things to modify in the design before the project get approved, it is about the styling, and your contact form is missing a background image, take a look at this image below and please fix that.

<img width="1269" alt="yes" src="https://user-images.githubusercontent.com/77843050/206562744-7683e216-3ed8-414d-a653-cb30082d737f.png">

2022-12-08 21:10 UTC, joskalenda commented on index.html
>              <h1>Contact Me</h1>
- [x] This line over here, well, let me give you my opinion regarding the styling before we reach the project requirement, I don't think it really looks fine to add that text-shadow in it, and not a black one sorry, it is totally not matching the global design you see, so maybe you will not agree with my idea but it is okay 😄 , let take it into the project requirements, please make sure you remove it and keep the same design as the one in the original design, it would be nicer than this currently on.

<img width="821" alt="text" src="https://user-images.githubusercontent.com/77843050/206566420-9470b5c4-a524-47a8-9a06-76a3b44f5fcf.png">

2022-12-08 21:10 UTC, joskalenda commented on index.html
>              <h1>About <br>
- [ ] We are not done yet, it is said to use the same alignment as per the original design, well despite we are working on the desktop version already, I think you would want to take a few steps back to the mobile version and fix this below, from the `about me` section, I think we are missing some spaces on the left of the element in there, please adjust them and your work will be good to go, this is what I am talking about

<img width="431" alt="no" src="https://user-images.githubusercontent.com/77843050/206567350-30460a7e-f90d-41bc-b128-ac8184157036.png">

- [ ] Figma design

<img width="286" alt="fig" src="https://user-images.githubusercontent.com/77843050/206567784-e96031b7-5685-44a2-91ca-0972d9bbe40b.png">

2022-12-09 09:50 UTC, frank1738 approved these changes
Hi @cindykandie , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/1uC8xfkZRi7Kw/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good Design👍 
✅ Good PR Description👍 

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 10:45 UTC, merged